import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

/**
 * Everything under src/content is generated by the translator repo's publish
 * scripts. Never hand-edit it: the next publish overwrites it, and the translator
 * repo (plus the source repos it reads) is the source of truth.
 */

const STATUS = z.enum(["planned", "published"]);

/** A translated item. `planned` entries carry no body and get no detail page. */
const translations = defineCollection({
  // The default id is the bare filename, which collapses every language's copy of
  // a slug into one entry. Key on the full path instead: <lang>/<type>/<slug>.
  loader: glob({
    pattern: "**/*.md",
    base: "./src/content/translations",
    generateId: ({ entry }) => entry.replace(/\.md$/, "")
  }),
  schema: z.object({
    lang: z.string(),
    type: z.string(),
    slug: z.string(),
    /** Title in the target language. Absent while status is `planned`. */
    title: z.string().optional(),
    status: STATUS,
    /** Repo the translation was published from, e.g. front-end. */
    source_repo: z.string().optional(),
    /** Path to the English source within that repo. */
    source_path: z.string().optional(),
    /** md5 of the English source at publish time. Compared against the English
     *  snapshot to detect that the source moved on underneath the translation. */
    en_md5: z.string().optional(),
    /** translator-repo SHA whose guide + glossary this was built against. */
    governance_sha: z.string().optional(),
    published_at: z.string().optional(),
    /** Discourse topic where this translation is discussed. */
    forum_topic_id: z.number().optional()
  })
});

/** The English source, frozen at the moment its translation was published. */
const english = defineCollection({
  loader: glob({
    pattern: "**/*.md",
    base: "./src/content/english",
    generateId: ({ entry }) => entry.replace(/\.md$/, "")
  }),
  schema: z.object({
    type: z.string(),
    slug: z.string(),
    title: z.string(),
    en_md5: z.string(),
    source_repo: z.string(),
    source_path: z.string(),
    captured_at: z.string()
  })
});

const glossaryTerm = z.object({
  en: z.string(),
  target: z.string(),
  /** The glossary's "Use (xx/en)" column: which language the term is written in. */
  use: z.string().optional(),
  notes: z.string().optional(),
  /** Stable id so a forum comment can link one row: #term-loop */
  anchor: z.string()
});

const glossarySection = z.object({
  title: z.string(),
  /** Heading level, so the page can nest ### under ##. */
  level: z.number(),
  /** Whether these rows come from the shared family file or this locale's own. */
  scope: z.enum(["family", "locale"]),
  intro: z.string().optional(),
  terms: z.array(glossaryTerm)
});

const glossaries = defineCollection({
  loader: glob({ pattern: "*.json", base: "./src/content/glossaries" }),
  schema: z.object({
    lang: z.string(),
    family: z.string().nullable().optional(),
    governance_sha: z.string(),
    published_at: z.string(),
    sections: z.array(glossarySection),
    /** Discourse topic for glossary discussion, from forum-tracking.json. */
    forum_topic_id: z.number().optional()
  })
});

export const collections = { translations, english, glossaries };
