import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

/**
 * Everything under src/content is generated by the translator repo's publish
 * scripts. Never hand-edit it: the next publish overwrites it, and the translator
 * repo (plus the source repos it reads) is the source of truth.
 */

const STATUS = z.enum(["planned", "published"]);

/** A translated item. `planned` entries carry no body and get no detail page. */
const translations = defineCollection({
  // The default id is the bare filename, which collapses every language's copy of
  // a slug into one entry. Key on the full path instead: <lang>/<type>/<slug>.
  loader: glob({
    pattern: "**/*.md",
    base: "./src/content/translations",
    generateId: ({ entry }) => entry.replace(/\.md$/, "")
  }),
  schema: z.object({
    lang: z.string(),
    type: z.string(),
    slug: z.string(),
    /** Title in the target language. Absent while status is `planned`. */
    title: z.string().optional(),
    status: STATUS,
    /** Repo the translation was published from, e.g. front-end. */
    source_repo: z.string().optional(),
    /** Path to the English source within that repo. */
    source_path: z.string().optional(),
    /** md5 of the English source at publish time. Compared against the English
     *  snapshot to detect that the source moved on underneath the translation. */
    en_md5: z.string().optional(),
    /** translator-repo SHA whose guide + glossary this was built against. */
    governance_sha: z.string().optional(),
    /** Hash of the translated text. Readers' "reviewed" marks are keyed on it,
     *  so republishing changed content clears them and a no-op republish
     *  doesn't. */
    content_version: z.string().optional(),
    published_at: z.string().optional(),
    /** Exercises only: the i18next message catalogs, English and target side by
     *  side on one row. Data rather than body prose so the page can render them
     *  as one full-width table per namespace instead of pushing them through the
     *  two-column prose layout, which would print every key twice. A `null` cell
     *  means the key is missing from that side. */
    messages: z
      .array(
        z.object({
          heading: z.string(),
          note: z.string().optional(),
          namespaces: z.array(
            z.object({
              name: z.string(),
              rows: z.array(
                z.object({
                  key: z.string(),
                  english: z.string().nullable(),
                  target: z.string().nullable()
                })
              )
            })
          )
        })
      )
      .optional()
  })
});

/** The English source, frozen at the moment its translation was published. */
const english = defineCollection({
  loader: glob({
    pattern: "**/*.md",
    base: "./src/content/english",
    generateId: ({ entry }) => entry.replace(/\.md$/, "")
  }),
  schema: z.object({
    type: z.string(),
    slug: z.string(),
    title: z.string(),
    en_md5: z.string(),
    source_repo: z.string(),
    source_path: z.string(),
    captured_at: z.string()
  })
});

/**
 * A language's agreed glossary, published as the Markdown it is written in.
 *
 * Deliberately unparsed. The translator repo used to normalise glossary.md into
 * sections and terms, and the normalisation silently dropped every table whose
 * first column wasn't headed "English" (about a quarter of every glossary). The
 * glossary is written for an LLM to read during a translation pass, so its
 * Markdown is the right format and this site adapts to it, not the reverse.
 * Nothing here interprets the tables, so nothing here can drop a row.
 *
 * For a family locale (es-419, pt-BR, zh-CN) the body is the family glossary
 * followed by the locale's own, separated by a rule.
 */
const glossaries = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/glossaries" }),
  schema: z.object({
    lang: z.string(),
    name: z.string().optional(),
    family: z.string().nullable().optional(),
    /** Review stage: how far this language has progressed. See STAGES in lib/languages.ts. */
    stage: z.enum(["setup", "refining", "reviewing"]).optional(),
    governance_sha: z.string(),
    /** Hash of the published Markdown. See the note on the translations collection. */
    content_version: z.string().optional(),
    published_at: z.string(),
    /** Table rows in the body. A reported count for the chrome, nothing selects on it. */
    term_count: z.number().optional(),
    /** Discourse topic for glossary discussion, from the language's tracking.json. */
    forum_topic_id: z.number().optional(),
    /** Discourse topic for the video player page, also from tracking.json. The
     *  player has no translated file behind it (its wording is Video.js's, not
     *  ours), so this language record is where the site keeps its thread. */
    video_player_forum_topic_id: z.number().optional()
  })
});

export const collections = { translations, english, glossaries };
